### ISSUE TITLE
Global variables not being complied in dist

### ISSUE THREAD

**Issue by nicolemors** [cloudfour/drizzle#93]
I am pretty sure this is an issue with `postcss-cssnext`... but I can't figure it out. I even tried their [glitter chat](https://gitter.im/MoOx/postcss-cssnext?at=58960e541319d8183ef093a7). 

I am using Drizzle for a project and variables just stopped working, I also downloaded a fresh instance of Drizzle and I had the same issue 😑 :
![no-variables](https://cloud.githubusercontent.com/assets/1895290/22620993/aa0f8a5c-eacd-11e6-93cd-7a6462c6221b.png)

When I comment out `@use postcss-cssnext;` its business as usual, but no cssnext goodness 😑 : 
![no-cssnext](https://cloud.githubusercontent.com/assets/1895290/22620994/aa11a4ae-eacd-11e6-977b-40a217bf666c.png)

**Comment by erikjung** [comment]
> I am using Drizzle for a project and variables just stopped working

@nicolemors Can you expand on that a bit? PostCSS uses this plugin to handle custom properties: https://github.com/postcss/postcss-custom-properties

The expected output would not have your `:root` definitions in it (unless you configured the plugin using the `preserve` option). The main function of the plugin is to replace the property _references_ with their corresponding values:

### Input

```css
:root {
  --myColor: red;
}

body {
  color: var(--myColor);
}
```

### Output

```css
body {
  color: red;
}
```

If you add `color(--color-red)` to your `html` selector, what shows up in the output?

This?

```css
html {
  color: #ff4136;
  line-height: 1.5;
}
```

or this?

```css
html {
  color: color(--color-red);
  line-height: 1.5;
}
```
